Examples/QuickStart/QuickStart/Models/ErrorViewModel.cs
namespace QuickStart.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examples/QuickStart/QuickStart/Controllers/AccountController.cs
using EVEClient.NET.Identity.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace QuickStart.Controllers
{
    public class AccountController : Controller
    {
        public async Task<IActionResult> Login(string returnUrl)
        {
            return await this.EveChallengeAsync(returnUrl);
        }

        public async Task<IActionResult> Logout(string returnUrl)
        {
            // removes auth cookie
            // clean tokens store
            // revokes refresh token on the ESI SSO side
            await HttpContext.EveSingOutAsync();

            return Redirect(returnUrl);
        }
    }
}

Examples/QuickStart/QuickStart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuickStart.Models;
using System.Diagnostics;

namespace QuickStart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examples/QuickStart/QuickStart/Controllers/ProtectedController.cs
using EVEClient.NET;
using EVEClient.NET.DataContract;
using EVEClient.NET.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace QuickStart.Controllers
{
    [Authorize]
    public class ProtectedController : Controller
    {
        private readonly IEsiLogicAccessor _logicAccessor;
        private readonly IEveUserAccessor<EveOnlineUser> _userAccessor;
        
        public ProtectedController(IEsiLogicAccessor logicAccessor, IEveUserAccessor<EveOnlineUser> userAccessor)
        { 
            _logicAccessor = logicAccessor;
            _userAccessor = userAccessor;
        }

        public async Task<IActionResult> Index()
        {
            var mails = await _logicAccessor.MailLogic.MailHeaders(_userAccessor.Current!.CharacterId);
            if (mails.Success)
            { 
                return View(mails.Data);
            }

            return View(new List<Header>());
        }
    }
}

Examples/QuickStart/QuickStart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examples/QuickStart/QuickStart/Views/Protected/Index.cshtml
@using EVEClient.NET.Identity
@using EVEClient.NET.DataContract

@model List<Header>

@{
    ViewData["Title"] = "Protected Page";
}

<h4>MailBox</h4>

<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">From</th>
            <th scope="col">Read</th>
            <th scope="col">Subject</th>
            <th scope="col">Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var mail in @Model)
        {
            <tr>
                <th scope="row">@mail.From</th>
                <td>
                    <div>
                        @if (mail.IsRead == true)
                        {
                            <input class="form-check-input" type="checkbox" id="checkboxNoLabel" checked value="" aria-label="..." disabled>
                        }
                        else
                        {
                            <input class="form-check-input" type="checkbox" id="checkboxNoLabel" value="" aria-label="..." disabled>
                        }
                    </div>
                </td>
                <td>@mail.Subject</td>
                <td>@mail.Timestamp</td>
            </tr>
        }
    </tbody>
</table>

Examples/QuickStart/QuickStart/Views/Shared/_Layout.cshtml
@using EVEClient.NET.Identity

@inject IEveUserAccessor<EveOnlineUser> UserAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuickStart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuickStart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuickStart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (UserAccessor.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Protected" asp-action="Index">Mailbox</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QuickStart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>